/**
 * 
 * @authors Your Name (you@example.org)
 * @date    2017-09-12 17:53:09
 * @version $Id$
 */

var navOptions = {
    styles:{
        logo:{
            imgUrl:'images/logo.png',
            linkUrl:'http://www.jiajiadata.com'
        },
        showMore:true,
    },
    firstClass:[{
        hasScd:false,
        pageName:'用户管理',
        pageId:'page1',
        linkUrl:'#1'
    },{
        hasScd:false,
        pageName:'代理商管理',
        pageId:'page2',
        linkUrl:'#2'
    },{
        hasScd:true,
        pageName:'短信管理',
        pageId:'page3',
        secondClass:[{
            pageName:'短信模板管理',
            pageId:'page3_1',
            linkUrl:'#31'
        },{
            pageName:'短信通道管理',
            pageId:'page3_2',
            linkUrl:'#32' 
        }]
    },{
        hasScd:false,
        pageName:'广告管理',
        pageId:'page4',
        linkUrl:'#4'
    },{
        hasScd:true,
        pageName:'财务管理',
        pageId:'page5',
        secondClass:[{
            pageName:'充值',
            pageId:'page5_1',
            linkUrl:'#51'
        },{
            pageName:'充值记录',
            pageId:'page5_2',
            linkUrl:'#52' 
        },{
            pageName:'退款',
            pageId:'page5_3',
            linkUrl:'#53' 
        },{
            pageName:'退款记录',
            pageId:'page5_4',
            linkUrl:'#54' 
        },{
            pageName:'申请开票',
            pageId:'page5_5',
            linkUrl:'#55' 
        },{
            pageName:'申请开票记录',
            pageId:'page5_6',
            linkUrl:'#56' 
        },{
            pageName:'用户账户明细',
            pageId:'page5_7',
            linkUrl:'#57' 
        },{
            pageName:'代理商账户明细',
            pageId:'page5_8',
            linkUrl:'#58' 
        }]
    },{
        hasScd:true,
        pageName:'统计报表',
        pageId:'page6',
        secondClass:[{
            pageName:'直客实消报表',
            pageId:'page6_1',
            linkUrl:'#61'
        },{
            pageName:'代理商实消报表',
            pageId:'page6_2',
            linkUrl:'#62' 
        },{
            pageName:'返佣记录报表',
            pageId:'page6_3',
            linkUrl:'#63' 
        },{
            pageName:'结算报表',
            pageId:'page6_4',
            linkUrl:'#64' 
        },{
            pageName:'客户经理绩效',
            pageId:'page6_5',
            linkUrl:'#65' 
        },{
            pageName:'市场运营绩效',
            pageId:'page6_6',
            linkUrl:'#66' 
        },{
            pageName:'客户实消流水',
            pageId:'page6_7',
            linkUrl:'#67' 
        }]
    },{
        hasScd:true,
        pageName:'中间号管理',
        pageId:'page7',
        secondClass:[{
            pageName:'中间号列表',
            pageId:'page7_1',
            linkUrl:'#71'
        },{
            pageName:'中间号分配管理',
            pageId:'page7_2',
            linkUrl:'#72' 
        }]
    },{
        hasScd:true,
        pageName:'系统管理',
        pageId:'page8',
        secondClass:[{
            pageName:'帐号管理',
            pageId:'page8_1',
            linkUrl:'#81'
        },{
            pageName:'角色管理',
            pageId:'page8_2',
            linkUrl:'#82' 
        },{
            pageName:'重置用户密码',
            pageId:'page8_3',
            linkUrl:'#83' 
        },{
            pageName:'重置代理商密码',
            pageId:'page8_4',
            linkUrl:'#84' 
        },{
            pageName:'日志管理',
            pageId:'page8_5',
            linkUrl:'#85' 
        },]
    }]
}